[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clippy_fix]
command = "cargo"
args = ["clippy", "--fix"]


[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.clean]
command = "cargo"
args = ["clean"]
