//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::artists::Entity as Artists;
pub use super::artists_tracks::Entity as ArtistsTracks;
pub use super::scrobbles::Entity as Scrobbles;
pub use super::tracks::Entity as Tracks;
