//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::albums_artists::Entity")]
    AlbumsArtists,
    #[sea_orm(has_many = "super::albums_tracks::Entity")]
    AlbumsTracks,
}

impl Related<super::albums_artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsArtists.def()
    }
}

impl Related<super::albums_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlbumsTracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
