//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "artists")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artists_tracks::Entity")]
    ArtistsTracks,
}

impl Related<super::artists_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistsTracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
