//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub mod prelude;

pub mod albums;
pub mod albums_artists;
pub mod albums_tracks;
pub mod artists;
pub mod artists_tracks;
pub mod scrobbles;
pub mod tags;
pub mod tags_tracks;
pub mod tracks;
