//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tags_tracks::Entity")]
    TagsTracks,
}

impl Related<super::tags_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TagsTracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
