//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tracks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    pub duration_secs: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::scrobbles::Entity")]
    Scrobbles,
}

impl Related<super::scrobbles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scrobbles.def()
    }
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        super::artists_tracks::Relation::Artists.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::artists_tracks::Relation::Tracks.def().rev())
    }
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        super::albums_tracks::Relation::Albums.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::albums_tracks::Relation::Tracks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
