//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tracks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    pub length: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::scrobbles::Entity")]
    Scrobbles,
    #[sea_orm(has_many = "super::artists_tracks::Entity")]
    ArtistsTracks,
}

impl Related<super::scrobbles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scrobbles.def()
    }
}

impl Related<super::artists_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistsTracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
